In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('student.csv')

In [9]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [10]:
df.shape

(10, 5)

In [11]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    10 non-null     int64
 1   name    10 non-null     object
 2   class   10 non-null     object
 3   marks   10 non-null     float64
 4   age     10 non-null     int64
dtypes: float64(1), int64(2), object(2)
memory usage: 532.0+ bytes

In [13]:
df.head()

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20

In [14]:
df.head(7)

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19

In [15]:
df.tail()

   roll    name class  marks  age
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [16]:
df.tail(6)

   roll    name class  marks  age
4     5    asha    TE  63.28   20
5     6  ayesha    BE  49.55   20
6     7    amar    BE  65.34   19
7     8   amita    BE  68.33   23
8     9    amol    TE  56.75   20
9    10   anmol    BE  78.66   21

In [17]:
df.tail(3)

   roll   name class  marks  age
7     8  amita    BE  68.33   23
8     9   amol    TE  56.75   20
9    10  anmol    BE  78.66   21

In [18]:
df.values

array([[1, 'anil', 'TE', 56.77, 22],
       [2, 'amit', 'TE', 59.77, 21],
       [3, 'aniket', 'BE', 76.88, 19],
       [4, 'ajinkya', 'TE', 69.66, 20],
       [5, 'asha', 'TE', 63.28, 20],
       [6, 'ayesha', 'BE', 49.55, 20],
       [7, 'amar', 'BE', 65.34, 19],
       [8, 'amita', 'BE', 68.33, 23],
       [9, 'amol', 'TE', 56.75, 20],
       [10, 'anmol', 'BE', 78.66, 21]], dtype=object)

In [19]:
"""
# slicing
   Index based -> loc
   column name -> iloc
""";

In [20]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [21]:
df.iloc[1:4,1:4]

      name class  marks
1     amit    TE  59.77
2   aniket    BE  76.88
3  ajinkya    TE  69.66

In [22]:
df.iloc[1:5,[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28

In [23]:
df.iloc[[1,2,3,4,6],[0,1,3]]

   roll     name  marks
1     2     amit  59.77
2     3   aniket  76.88
3     4  ajinkya  69.66
4     5     asha  63.28
6     7     amar  65.34

In [24]:
df.replace('ayesha','geet')     # if ayesha is repeated many times this will not work

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [25]:
df.iloc[5,1] = 'geet'

In [26]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [27]:
#loc

In [28]:
df.loc[2:5,'name']

2     aniket
3    ajinkya
4       asha
5       geet
Name: name, dtype: object

In [29]:
df.loc[2:5,['name','class']]

      name class
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE

In [30]:
df.loc[0:10,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [31]:
df.loc[:,'name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [32]:
df['name']

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [33]:
df[['name','class']]

      name class
0     anil    TE
1     amit    TE
2   aniket    BE
3  ajinkya    TE
4     asha    TE
5     geet    BE
6     amar    BE
7    amita    BE
8     amol    TE
9    anmol    BE

In [34]:
# methods on coloumns/series

In [35]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [36]:
df['name'].str.upper()                       # here we cannot directly use upper() becoz column is of object not string  so we use str

0       ANIL
1       AMIT
2     ANIKET
3    AJINKYA
4       ASHA
5       GEET
6       AMAR
7      AMITA
8       AMOL
9      ANMOL
Name: name, dtype: object

In [37]:
df['name'].str.lower()

0       anil
1       amit
2     aniket
3    ajinkya
4       asha
5       geet
6       amar
7      amita
8       amol
9      anmol
Name: name, dtype: object

In [38]:
#add or modify the coloumns

In [39]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6     geet    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [40]:
gender = ['m','f','m','m','f','f','f','m','f','m']

In [41]:
df['gender'] = gender

In [42]:
df

   roll     name class  marks  age gender
0     1     anil    TE  56.77   22      m
1     2     amit    TE  59.77   21      f
2     3   aniket    BE  76.88   19      m
3     4  ajinkya    TE  69.66   20      m
4     5     asha    TE  63.28   20      f
5     6     geet    BE  49.55   20      f
6     7     amar    BE  65.34   19      f
7     8    amita    BE  68.33   23      m
8     9     amol    TE  56.75   20      f
9    10    anmol    BE  78.66   21      m

In [43]:
df['roll'] = df['roll'] + 100

In [44]:
df

   roll     name class  marks  age gender
0   101     anil    TE  56.77   22      m
1   102     amit    TE  59.77   21      f
2   103   aniket    BE  76.88   19      m
3   104  ajinkya    TE  69.66   20      m
4   105     asha    TE  63.28   20      f
5   106     geet    BE  49.55   20      f
6   107     amar    BE  65.34   19      f
7   108    amita    BE  68.33   23      m
8   109     amol    TE  56.75   20      f
9   110    anmol    BE  78.66   21      m

In [45]:
# add a new column cgpa
# values should  => marks/10 +1.5

In [46]:
df['cgpa'] = df['marks']/10 + 1.5

In [47]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [48]:
df.sort_values(by = 'name')

   roll     name class  marks  age gender   cgpa
3   104  ajinkya    TE  69.66   20      m  8.466
6   107     amar    BE  65.34   19      f  8.034
1   102     amit    TE  59.77   21      f  7.477
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
2   103   aniket    BE  76.88   19      m  9.188
0   101     anil    TE  56.77   22      m  7.177
9   110    anmol    BE  78.66   21      m  9.366
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455

In [49]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [50]:
# sort by class and then marks simultaneously and check the result

In [51]:
df.sort_values(by = ['name','marks'])

   roll     name class  marks  age gender   cgpa
3   104  ajinkya    TE  69.66   20      m  8.466
6   107     amar    BE  65.34   19      f  8.034
1   102     amit    TE  59.77   21      f  7.477
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
2   103   aniket    BE  76.88   19      m  9.188
0   101     anil    TE  56.77   22      m  7.177
9   110    anmol    BE  78.66   21      m  9.366
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455

In [52]:
df['marks'].mean()

np.float64(64.499)

In [53]:
df['marks'].max()

78.66

In [54]:
df['marks'].max()

78.66

In [55]:
# groupby

In [56]:
gr = df.groupby('class')

In [57]:
gr.groups

{'BE': [2, 5, 6, 7, 9], 'TE': [0, 1, 3, 4, 8]}

In [58]:
gr.get_group('BE')

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
5   106    geet    BE  49.55   20      f  6.455
6   107    amar    BE  65.34   19      f  8.034
7   108   amita    BE  68.33   23      m  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [59]:
gr.get_group('TE')

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
8   109     amol    TE  56.75   20      f  7.175

In [60]:
gr.min()

       roll     name  marks  age gender   cgpa
class
BE      103     amar  49.55   19      f  6.455
TE      101  ajinkya  56.75   20      f  7.175

In [61]:
gr['marks'].mean()

class
BE    67.752
TE    61.246
Name: marks, dtype: float64

In [62]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [63]:
df['marks']>60

0    False
1    False
2     True
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: marks, dtype: bool

In [64]:
df[df['marks']>60]

   roll     name class  marks  age gender   cgpa
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
9   110    anmol    BE  78.66   21      m  9.366

In [65]:
# filter the data of those students -> marks -> 60 and belong to be class

In [66]:
df[(df['class']=='BE') &(df['marks']>60)]

   roll    name class  marks  age gender   cgpa
2   103  aniket    BE  76.88   19      m  9.188
6   107    amar    BE  65.34   19      f  8.034
7   108   amita    BE  68.33   23      m  8.333
9   110   anmol    BE  78.66   21      m  9.366

In [67]:
df.drop(4)

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [68]:
df.drop([4,5,6])

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [69]:
# drop column name

In [70]:
df.drop(columns ='name')

   roll class  marks  age gender   cgpa
0   101    TE  56.77   22      m  7.177
1   102    TE  59.77   21      f  7.477
2   103    BE  76.88   19      m  9.188
3   104    TE  69.66   20      m  8.466
4   105    TE  63.28   20      f  7.828
5   106    BE  49.55   20      f  6.455
6   107    BE  65.34   19      f  8.034
7   108    BE  68.33   23      m  8.333
8   109    TE  56.75   20      f  7.175
9   110    BE  78.66   21      m  9.366

In [71]:
df.drop('name',axis = 1)            #work rowwise so we have to provide axis

   roll class  marks  age gender   cgpa
0   101    TE  56.77   22      m  7.177
1   102    TE  59.77   21      f  7.477
2   103    BE  76.88   19      m  9.188
3   104    TE  69.66   20      m  8.466
4   105    TE  63.28   20      f  7.828
5   106    BE  49.55   20      f  6.455
6   107    BE  65.34   19      f  8.034
7   108    BE  68.33   23      m  8.333
8   109    TE  56.75   20      f  7.175
9   110    BE  78.66   21      m  9.366

In [72]:
# drop name and class

In [73]:
df.drop(['name','class'],axis = 1)

   roll  marks  age gender   cgpa
0   101  56.77   22      m  7.177
1   102  59.77   21      f  7.477
2   103  76.88   19      m  9.188
3   104  69.66   20      m  8.466
4   105  63.28   20      f  7.828
5   106  49.55   20      f  6.455
6   107  65.34   19      f  8.034
7   108  68.33   23      m  8.333
8   109  56.75   20      f  7.175
9   110  78.66   21      m  9.366

In [74]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [75]:
df

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [76]:
df
#create a dataframe newdf
#coloumns -> row ,gender ,cgpa
# roll column will have the same values as the df dataframe

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366

In [77]:
newdf = pd.DataFrame({
    'roll':df['roll'],
    'genger':gender,
    'cgpa':df['marks']/10 + 1.5
})
newdf

   roll genger   cgpa
0   101      m  7.177
1   102      f  7.477
2   103      m  9.188
3   104      m  8.466
4   105      f  7.828
5   106      f  6.455
6   107      f  8.034
7   108      m  8.333
8   109      f  7.175
9   110      m  9.366

In [78]:
pd.merge(df,newdf)

   roll     name class  marks  age gender   cgpa genger
0   101     anil    TE  56.77   22      m  7.177      m
1   102     amit    TE  59.77   21      f  7.477      f
2   103   aniket    BE  76.88   19      m  9.188      m
3   104  ajinkya    TE  69.66   20      m  8.466      m
4   105     asha    TE  63.28   20      f  7.828      f
5   106     geet    BE  49.55   20      f  6.455      f
6   107     amar    BE  65.34   19      f  8.034      f
7   108    amita    BE  68.33   23      m  8.333      m
8   109     amol    TE  56.75   20      f  7.175      f
9   110    anmol    BE  78.66   21      m  9.366      m

In [79]:
# concat

In [80]:
# load  student5.csv

In [81]:
da = pd.read_csv('student5.csv')

In [82]:
da

   roll     name class  marks  age
0     1   surbhi    TE  67.44   23
1     2    sujay    TE  74.12   22
2     3  subhash    BE  82.44   21
3     4   sachin    TE  59.33   21
4     5  shalini    TE  63.45   20

In [83]:
pd.concat([df,da])              # but has index problem

   roll     name class  marks  age gender   cgpa
0   101     anil    TE  56.77   22      m  7.177
1   102     amit    TE  59.77   21      f  7.477
2   103   aniket    BE  76.88   19      m  9.188
3   104  ajinkya    TE  69.66   20      m  8.466
4   105     asha    TE  63.28   20      f  7.828
5   106     geet    BE  49.55   20      f  6.455
6   107     amar    BE  65.34   19      f  8.034
7   108    amita    BE  68.33   23      m  8.333
8   109     amol    TE  56.75   20      f  7.175
9   110    anmol    BE  78.66   21      m  9.366
0     1   surbhi    TE  67.44   23    NaN    NaN
1     2    sujay    TE  74.12   22    NaN    NaN
2     3  subhash    BE  82.44   21    NaN    NaN
3     4   sachin    TE  59.33   21    NaN    NaN
4     5  shalini    TE  63.45   20    NaN    NaN

In [84]:
pd.concat([df,da] , ignore_index = True)          # improvrd version

    roll     name class  marks  age gender   cgpa
0    101     anil    TE  56.77   22      m  7.177
1    102     amit    TE  59.77   21      f  7.477
2    103   aniket    BE  76.88   19      m  9.188
3    104  ajinkya    TE  69.66   20      m  8.466
4    105     asha    TE  63.28   20      f  7.828
5    106     geet    BE  49.55   20      f  6.455
6    107     amar    BE  65.34   19      f  8.034
7    108    amita    BE  68.33   23      m  8.333
8    109     amol    TE  56.75   20      f  7.175
9    110    anmol    BE  78.66   21      m  9.366
10     1   surbhi    TE  67.44   23    NaN    NaN
11     2    sujay    TE  74.12   22    NaN    NaN
12     3  subhash    BE  82.44   21    NaN    NaN
13     4   sachin    TE  59.33   21    NaN    NaN
14     5  shalini    TE  63.45   20    NaN    NaN

In [85]:
f = df[(df['class']=='BE') &(df['marks']>60)]

In [86]:
f.to_csv('op.csv', index = False)