In [1]:
#studen1.csv

In [2]:
import pandas  as pd
import numpy as np

In [16]:
df = pd.read_csv('student3.csv')
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [17]:
df.shape

(16, 5)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   roll    16 non-null     int64
 1   name    16 non-null     object
 2   class   15 non-null     object
 3   marks   14 non-null     float64
 4   age     14 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 772.0+ bytes

In [19]:
#fix structural error

In [20]:
df['name']

0        anil
1        amit
2      aniket
3     ajinkya
4        asha
5      ayesha
6        amar
7       Amita
8        amol
9        amol
10      anmol
11     surbhi
12      Sujay
13    subhash
14     sachin
15    shalini
Name: name, dtype: object

In [21]:
df['name] = df['name'].str.title()

SyntaxError: unterminated string literal (detected at line 1) (671456042.py, line 1)

In [22]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [23]:
df.drop_duplicates(inplace=True)

In [24]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [25]:
df.count()

roll      15
name      15
class     14
marks     13
age       13
dtype: int64

In [26]:
df.isnull().sum()

roll      0
name      0
class     1
marks     2
age       2
dtype: int64

In [27]:
df.isnull().sum().sum()

np.int64(5)

In [28]:
#removing rows with null values

In [29]:
df.dropna()

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
15    15  shalini    TE   63.45  20.0

In [30]:
#filling the missing values

In [40]:
df['roll'].fillna(45)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
10    10
11    11
12    12
13    13
14    14
15    15
Name: roll, dtype: int64

In [56]:
df['roll'].mean()

np.float64(8.0)

In [43]:
#fill class column value with mode

In [54]:
df['class'].mode()

0    TE
Name: class, dtype: object

In [58]:
df['class'].fillna(df['class'].mode()[0])

0     TE
1     TE
2     BE
3     TE
4     TE
5     BE
6     BE
7     be
8     TE
10    BE
11    TE
12    TE
13    be
14    TE
15    TE
Name: class, dtype: object

In [59]:
df.ffill()

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28  20.0
5      6   ayesha    BE   63.28  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66  20.0
11    11   surbhi    TE   78.66  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin    TE   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [60]:
df.bfill()

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28  20.0
5      6   ayesha    BE   65.34  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66  23.0
11    11   surbhi    TE   74.12  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin    TE   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [61]:
df.bfill(inplace=True)

In [62]:
df.isnull().sum()

roll      0
name      0
class     0
marks     0
age       0
dtype: int64